GTI_MVC/Controllers/sysImobController.cs
using GTI_Bll.Classes;
using GTI_Models.Models;
using GTI_Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static GTI_Models.modelCore;

namespace GTI_Mvc.Controllers
{
    public class sysImobController : Controller   {
        private readonly string _connection = "GTIconnection";

        [Route("imovel_query")]
        [HttpGet]
        public ActionResult imovel_query(string id) {
            ImovelDetailsViewModel model = new ImovelDetailsViewModel();
            model.Lista_Imovel = new List<ImovelLista>();
            return View(model);
        }

        [Route("imovel_query")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult imovel_query(ImovelDetailsViewModel model) {
            Imovel_bll imovelRepository = new Imovel_bll(_connection);
            model.Lista_Imovel = new List<ImovelLista>();
            int _codigo = Convert.ToInt32(model.Codigo);
            string _partialName = model.NomeProprietario ?? "";
            if (_partialName != "") {
                if (_partialName.Length < 5) {
                    ViewBag.Result = "Digite ao menos 5 caracteres do nome do proprietário.";
                    return View(model);
                }
            }
            string _partialEndereco = model.NomeEndereco ?? "";
            if (_partialEndereco != "") {
                if (_partialEndereco.Length < 5) {
                    ViewBag.Result = "Digite ao menos 5 caracteres do endereço.";
                    return View(model);
                }
            }
            int _numero = model.Numero == null ? 0 : Convert.ToInt32(model.Numero);
            int _distrito = 0, _setor = 0, _quadra = 0, _lote = 0, _face = 0, _unidade = 0, _subunidade = 0;
            string _insc = model.Inscricao ?? "";

            if (_insc != "") {
                if (_insc.Length == 25) {
                    _insc = Functions.RetornaNumero(model.Inscricao);
                    _distrito = Convert.ToInt32(_insc.Substring(0, 1));
                    _setor = Convert.ToInt32(_insc.Substring(1, 2));
                    _quadra = Convert.ToInt32(_insc.Substring(3, 4));
                    _lote = Convert.ToInt32(_insc.Substring(7, 5));
                    _face = Convert.ToInt32(_insc.Substring(12, 2));
                    _unidade = Convert.ToInt32(_insc.Substring(14, 2));
                    _subunidade = Convert.ToInt32(_insc.Substring(16, 3));
                } else {
                    ViewBag.Result = "Inscrição cadastral inválida.";
                    return View(model);
                }
            }

            if (_codigo == 0 && _insc == "" && _partialEndereco == "" && _partialName == "") {
                ViewBag.Result = "Selecione ao menos um critério de busca.";
                return View(model);
            }

            List<ImovelStruct> ListaImovel = imovelRepository.Lista_Imovel(_codigo, _distrito, _setor, _quadra, _lote, _face, _unidade, _subunidade, _partialName, _partialEndereco, _numero);
            if (ListaImovel.Count == 0) {
                ViewBag.Result = "Não foi localizado nenhum imóvel com este(s) critério(s).";
                return View(model);
            }
            List<ImovelLista> _lista = new List<ImovelLista>();
            foreach (ImovelStruct item in ListaImovel) {
                ImovelLista reg = new ImovelLista() {
                    Codigo = item.Codigo.ToString("00000"),
                    Nome = Functions.TruncateTo(item.Proprietario_Nome, 30),
                    Endereco = string.IsNullOrEmpty(item.NomeLogradouroAbreviado) ? item.NomeLogradouro : item.NomeLogradouroAbreviado
                };
                reg.Endereco += ", " + item.Numero.ToString() + " " + item.Complemento;
                reg.Endereco = Functions.TruncateTo(reg.Endereco, 52);
                _lista.Add(reg);
            }

            model.Lista_Imovel = _lista;
            return View(model);

        }

        [HttpGet]
        [Route("imovel_data")]
        public ActionResult imovel_data(string cod) {
            ImovelDetailsViewModel model = new ImovelDetailsViewModel();
            Imovel_bll imovelRepository = new Imovel_bll(_connection);
            string _guid = Guid.NewGuid().ToString("N");
            ViewBag.Codigo = cod;
            ViewBag.Guid = _guid;
            cod = Functions.RetornaNumero(cod);
            if (cod == "") {
                ViewBag.Result = "Código inválido.";
                return View(model);
            }
            int _codigo = Convert.ToInt32(cod);
            bool existe = imovelRepository.Existe_Imovel(_codigo);
            if (existe) {
                model.ImovelStruct = imovelRepository.Dados_Imovel(_codigo);
                model.Lista_Proprietario = imovelRepository.Lista_Proprietario(_codigo, false);
                model.Lista_Areas = imovelRepository.Lista_Area(_codigo);
                model.Lista_Testada = imovelRepository.Lista_Testada(_codigo);
                model.Tipo_Matricula = model.ImovelStruct.TipoMat == "T" ? "Transcrição" : "Matrícula";
                if (model.ImovelStruct.EE_TipoEndereco != null) {
                    short _tipoEE = (short)model.ImovelStruct.EE_TipoEndereco;
                    if (_tipoEE == 0)
                        model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Local);
                    else {
                        if (_tipoEE == 1)
                            model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Proprietario);
                        else
                            model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Entrega);
                    }
                }
            } else
                ViewBag.Result = "Imóvel não cadastrado.";

            return View(model);

        }

        [HttpGet]
        [Route("imovel_edit")]
        public ActionResult imovel_edit(string c) {
            ImovelDetailsViewModel model = new ImovelDetailsViewModel();
            W_Imovel_bll w_imovelRepository = new W_Imovel_bll(_connection);
            WImovel_Main w_main = w_imovelRepository.Retorna_Imovel_Main(c);
            if (w_main == null)
                return RedirectToAction("imovel_query");

            Imovel_bll imovelRepository = new Imovel_bll(_connection);
            int _codigo = w_main.Codigo;
            model.ImovelStruct = imovelRepository.Dados_Imovel(_codigo);

            ViewBag.Codigo = _codigo;
            ViewBag.Guid = w_main.Guid;
            ViewBag.TipoEnd = model.ImovelStruct.EE_TipoEndereco;
            ViewBag.Imune = model.ImovelStruct.Imunidade==null?false:model.ImovelStruct.Imunidade;
            ViewBag.Cip = model.ImovelStruct.Cip==null?false:model.ImovelStruct.Cip;
            ViewBag.Conjugado = model.ImovelStruct.Conjugado == null ? false : model.ImovelStruct.Conjugado;
            ViewBag.Reside = model.ImovelStruct.ResideImovel == null ? false : model.ImovelStruct.ResideImovel;
            if (model.ImovelStruct.EE_TipoEndereco != null) {
                short _tipoEE = (short)model.ImovelStruct.EE_TipoEndereco;
                if (_tipoEE == 0)
                    model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Local);
                else {
                    if (_tipoEE == 1)
                        model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Proprietario);
                    else
                        model.Endereco_Entrega = imovelRepository.Dados_Endereco(_codigo, TipoEndereco.Entrega);
                }
            }
            List<Topografia> listaTop = imovelRepository.Lista_Topografia();
            ViewBag.ListaTop = new SelectList(listaTop, "Codtopografia", "Desctopografia");
            List<Situacao> listaSit = imovelRepository.Lista_Situacao();
            ViewBag.ListaSit = new SelectList(listaSit, "Codsituacao", "Descsituacao");
            List<Categprop> listaCat = imovelRepository.Lista_Categoria_Propriedade();
            ViewBag.ListaCat = new SelectList(listaCat, "Codcategprop", "Desccategprop");
            List<Benfeitoria> listaBen = imovelRepository.Lista_Benfeitoria();
            ViewBag.ListaBen = new SelectList(listaBen, "Codbenfeitoria", "Descbenfeitoria");
            List<Pedologia> listaPed = imovelRepository.Lista_Pedologia();
            ViewBag.ListaPed = new SelectList(listaPed, "Codpedologia", "Descpedologia");
            List<Usoterreno> listaUso = imovelRepository.Lista_uso_terreno();
            ViewBag.ListaUso = new SelectList(listaUso, "Codusoterreno", "Descusoterreno");
            List<SelectListItem> ListaMat = new List<SelectListItem>();
            List<string> Lista_Mat = new List<string>();
            Lista_Mat.Add("Matrícula");
            Lista_Mat.Add("Transcrição");
            ViewBag.Lista_Matricula = new SelectList(Lista_Mat);
            if(model.ImovelStruct.TipoMat==null || model.ImovelStruct.TipoMat=="M")
                model.Tipo_Matricula = "Matrícula";
            else
                model.Tipo_Matricula = "Transcrição";
            
            //Save WImovel_Main
            WImovel_Main _mainR = new WImovel_Main() {
                Guid = w_main.Guid,
                Codigo = _codigo,
                Area_Terreno = model.ImovelStruct.Area_Terreno,
                Cip = model.ImovelStruct.Cip == null ? false : (bool)model.ImovelStruct.Cip,
                Imune = model.ImovelStruct.Imunidade == null ? false : (bool)model.ImovelStruct.Imunidade,
                Conjugado = model.ImovelStruct.Conjugado == null ? false : (bool)model.ImovelStruct.Conjugado,
                Reside = model.ImovelStruct.ResideImovel == null ? false : (bool)model.ImovelStruct.ResideImovel,
                Topografia = (short)model.ImovelStruct.Topografia,

GTI_MVC/Views/sysImob/imovel_query.cshtml
@model GTI_Mvc.ViewModels.ImovelDetailsViewModel

@{
    Layout = "~/Views/Shared/_Layoutgti.cshtml";
    ViewBag.Title = "Consulta de imóveis";
}

<style>

    .center {
        margin: auto;
    }

    .actionlink:hover {
        color: darkgreen;
    }

    .actionlink {
        color: darkslateblue;
    }

    .card-header {
        background-color: mistyrose;
        color: brown;
        font-size: 14px
    }

    .card {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    .card-footer {
        background-color: whitesmoke;
        font-size: 14px
    }

    .btn-primary {
        background-color: steelblue;
    }

    .btn {
        font-size: 14px;
        border-radius: 4px;
    }

    .modal-header {
        padding: 9px 15px;
        border-bottom: 1px solid #eee;
        background-color: darkslategrey;
        color: whitesmoke;
        -webkit-border-top-left-radius: 5px;
        -webkit-border-top-right-radius: 5px;
        -moz-border-radius-topleft: 5px;
        -moz-border-radius-topright: 5px;
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }

    .ui-dialog {
        z-index: 1060 !important;
    }

    .ui-dialog-titlebar-close {
        visibility: hidden;
    }

    .no-titlebar .ui-dialog-titlebar {
        display: none;
    }

    .uppercase {
        text-transform: uppercase
    }

    .ui-autocomplete {
        font-size: 13px;
        border-radius: 0px;
        border-color: maroon;
    }

    .highlight {
        background-color: #FFFFAF;
        color: Red;
        font-weight: bold;
        text-transform: uppercase
    }

    .ui-menu-item .ui-menu-item-wrapper.ui-state-active {
        background: darkred !important;
        font-weight: bold !important;
        color: #ffffff !important;
    }

    ul.ui-autocomplete {
        z-index: 1100;
    }

    .tbl tbody tr:hover {
        background-color: red;
        color: white;
    }

    tr.highlighted td {
        background: maroon;
        color: white;
    }

    .titulo {
        background: maroon;
        color: white;
        font-weight: normal;
        font-size: 13px;
    }

    .btnimage {
        border: 0 none;
        background: none;
        background-image: url('../../Images/cancelar.gif');
        width: 16px;
        height: 16px;
    }

    .btnimage2 {
        border: 0 none;
        background: none;
        background-image: url('../../Images/ok.png');
        width: 16px;
        height: 16px;
    }

    .shadow {
        -webkit-box-shadow: 3px 3px 5px 6px #ccc; /* Safari 3-4, iOS 4.0.2 - 4.2, Android 2.3+ */
        -moz-box-shadow: 3px 3px 5px 6px #ccc; /* Firefox 3.5 - 3.6 */
        box-shadow: 3px 3px 5px 6px #ccc; /* Opera 10.5, IE 9, Firefox 4+, Chrome 6+, iOS 5 */
    }

    .ellipsis {
        position: relative;
    }

        .ellipsis:before {
            content: '&nbsp;';
            visibility: hidden;
        }

        .ellipsis span {
            position: absolute;
            left: 0;
            right: 0;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }


    #mainTable thead {
        position: absolute;
        background-color: white;
    }

    #mainTable tbody {
        position: absolute;
        height: 262px;
        top: 210px;
        overflow: auto;
    }

    .modal-dialog {
        max-width: 430px; /* New width for default modal */
    }
</style>


@{var res = @ViewBag.Result; }

@using (Html.BeginForm("imovel_query", "sysImob", FormMethod.Post, new { @id = "MainForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" id="codTmp" >

    <div class="center shadow" style="width:760px">
        <div class="card">
            <div class="card-header">Consulta de imóveis</div>
            <div class="card-body">
                <div style="width: 100%; overflow: hidden;">
                    <div style="width: 600px; float: left;">
                        <table style="font-weight:normal;font-size:12px">
                            <tr>
                                <td>
                                    @if (Model.Codigo > 0)
                                    {
                                        @Html.TextBoxFor(m => m.Codigo, new { @id = "codigo", @style = "width:100px;height:25px", @onKeyPress = "return formata(this, '§§§§§', event)", @placeholder = "Código" })
                                    }
                                    else
                                    {
                                        @Html.TextBoxFor(m => m.Codigo, new { @id = "codigo", @style = "width:100px;height:25px", @onKeyPress = "return formata(this, '§§§§§', event)", @Value = "", @placeholder = "Código" })
                                    }
                                </td>
                                <td>
                                </td>
                                <td>
                                    @Html.TextBoxFor(m => m.Inscricao, new { @id = "codigo", @style = "width:250px;height:25px", @onKeyPress = "return formata(this, '§.§§.§§§§.§§§§§.§§.§§.§§§', event)", @placeholder = "Inscrição Cadastral" })
                                </td>
                            </tr>
                            <tr style="height:10px">
                                <td></td>
                            </tr>
                        </table>
                        <table style="font-weight:normal;font-size:12px">

                            <tr>
                                <td>
                                    @Html.TextBoxFor(m => m.NomeProprietario, new { @id = "nome", @style = "width:450px;height:25px", @placeholder = "Nome do proprietário" })
                                </td>
                            </tr>
                            <tr style="height:10px">
                                <td></td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.TextBoxFor(m => m.NomeEndereco, new { @id = "endereco", @style = "width:450px;height:25px", @placeholder = "Endereço do imóvel" })
                                </td>
                                <td style="width:10px"></td>
                                <td>
                                    @if (!string.IsNullOrEmpty(Model.Numero))
                                    {
                                        @Html.TextBoxFor(m => m.Numero, new { @id = "numero", @style = "width:80px;height:25px", @onKeyPress = "return formata(this, '§§§§', event)", @placeholder = "Número" })
                                    }
                                    else
                                    {
                                        @Html.TextBoxFor(m => m.Numero, new { @id = "numero", @style = "width:80px;height:25px", @onKeyPress = "return formata(this, '§§§§', event)", @Value = "", @placeholder = "Número" })
                                    }

                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="margin-left: 620px;">
                        <button id="btnCodigo" type="submit" style="margin-top:10px" class="btn btn-primary" name="action" value="btnCodigoOK">Consultar</button>
                    </div>
                </div>
            </div>
            <div id="table-container" style=" height: 290px; overflow: auto;border:solid;border-width:1px;width:720px;margin:auto">

                <table id="mainTable" class="tbl table-bordered table-condensed" style="width:680px;font-size:12px">
                    <thead style="background-color:darkblue;color:whitesmoke">
                        <tr style="height:10px">
                            <td style="width:50px;text-align:center">Código</td>
                            <td style="width:260px" ;text-align:left">Proprietário</td>
                            <td style="width:370px;text-align:left">Endereço</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (GTI_Models.Models.ImovelLista item in Model.Lista_Imovel)
                        {
                            <tr style="height: 20px; cursor: pointer">
                                <td style="width:50px;text-align:center;font-weight:normal">@Html.DisplayFor(modelItem => item.Codigo) </td>
                                <td style="width:260px;text-align:left;font-weight:normal">@Html.DisplayFor(modelItem => item.Nome) </td>
                                <td style="width:370px;text-align:left;font-weight:normal">@Html.DisplayFor(modelItem => item.Endereco) </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <br />
            <div class="card-footer" style="text-align:center;background-color:white">
                <button type="button" id="btValidar" class="btn btn-primary" style="height: 32px; margin-left: 10px;" title="Abrir o cadastro do imóvel selecionado " onclick="Abrir()">Abrir cadastro</button>&nbsp;&nbsp;
                <button type="button" id="btnFechar" class="btn btn-danger" style="height: 32px; margin-left: 10px; width: 80px" title="Fechar" onclick="Fechar()">Fechar</button>
            </div>

            <div class="card-footer">
                @Html.ActionLink("Retornar ao menu principal", "Login_gti", "Home", null, new { @class = "actionlink" })
            </div>
        </div>
    </div>
}

<div id="msgBox1" title="Atenção" style='display: none;'>
    <br />
    <label id="lblMsg"></label>
</div>
<div id="msgBoxBag" title="Atenção" style='display: none;'>
    <br />
    <p>@ViewBag.Result</p>
</div>
<div id="msgBoxWait" style='display: none;text-align:center'>
    <img src="~/Images/ajax-loader.gif"><br />
    <p>Processando, aguarde . . . </p>
</div>



@section scripts{

    <script type="text/javascript">

        $(document).ready(function () {


            $('#msgBox1').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });
             $('#msgBoxBag').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });
            $('#msgBoxWait').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "no-titlebar"
            });

            $(".foo .ui-dialog-title").css("font-size", "13px");
            $(".foo .ui-widget-content").css("font-size", "13px");

            $('.modal-dialog').draggable({
                handle: ".modal-header"
            });

            var _res = '@res';
            if (_res != "") {
                $('#msgBoxBag').dialog('open');
                return false;
            } else {
                return true;
            }
        });

        $("#mainTable").on('click', 'tr', function (e) {
            $('#mainTable tr').removeClass('highlighted');
            $(this).addClass('highlighted');
            document.getElementById('codTmp').value = $(this).closest('tr').find('td:eq(0)').text();
        });

        function Fechar() {
            var url = '@Url.Action("GtiSys", "Home")';
            window.location.href = url;
        }

        function Abrir() {
            var _cod = document.getElementById('codTmp').value;
            if (_cod == "" || parseInt(_cod) == 0) {
                document.getElementById('lblMsg').innerHTML = "Selecione um imóvel!";
                $('#msgBox1').dialog('open');
            } else {
                window.location.href = "localhost" ? "/sysImob/imovel_data?cod=" + _cod : "/gti/sysImob/imovel_data?cod=" + _cod;
            }
        }


        //######## Funções Genéricas #########
        function removeOptions(selectElement) {
            var i, L = selectElement.options.length - 1;
            for (i = L; i >= 0; i--) {
                selectElement.remove(i);
            }
        }

        function subNull(value) {
            return (value === null) ? "" : value;
        }

        function elementIsEmpty(el) {
            return (/^(\s|&nbsp;)*$/.test(el));
        }

        function pad(num, size) {
            num = num.toString();
            while (num.length < size) num = "0" + num;
            return num;
        }

        //####################################
    </script>
}