GTI_MVC/ViewModels/CidadaoViewModel.cs
using GTI_Models.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GTI_Mvc.ViewModels {
    public class CidadaoViewModel {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public string CpfCnpj { get; set; }
        public string Data_Nascto { get; set; }
        public string Rg_Numero { get; set; }
        public string Rg_Orgao { get; set; }
        public string Cnh_Numero { get; set; }
        public string Cnh_Orgao { get; set; }
        public int Profissao_Codigo { get; set; }
        public string Profissao_Nome { get; set; }
        public EnderecoStruct EnderecoR { get; set; }
        public EnderecoStruct EnderecoC { get; set; }
        public List<CidadaoHeader> Lista_Cidadao { get; set; }
    }

    


}

GTI_MVC/Controllers/CidadaoController.cs
using GTI_Bll.Classes;
using GTI_Models.Models;
using GTI_Mvc;
using GTI_Mvc.ViewModels;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GTI_MVC.Controllers {
    public class CidadaoController : Controller   {
        private readonly string _connection = "GTIconnection";

        [Route("Cidadao_menu")]
        [HttpGet]
        public ActionResult Cidadao_menu() {
            if (Session["hashid"] == null)
                return RedirectToAction("Login", "Home");

            return View();
        }

        [Route("Cidadao_chk")]
        [HttpGet]
        public ActionResult Cidadao_chk() {
            if (Session["hashid"] == null)
                return RedirectToAction("Login", "Home");

            CidadaoViewModel model = new CidadaoViewModel();

            return View(model);
        }

        [Route("Cidadao_chk")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Cidadao_chk(CidadaoViewModel model) {
            string _cpfcnpj = Functions.RetornaNumero(model.CpfCnpj);
            bool _bCpf = _cpfcnpj.Length == 11 ? true : false;
            bool _bCnpj = !_bCpf;

            Cidadao_bll cidadaoRepository = new Cidadao_bll(_connection);
            int _codigo = 0;
            if (_bCpf) {
                _codigo = cidadaoRepository.Existe_Cidadao_Cpf(_cpfcnpj);
            } else {
                _codigo = cidadaoRepository.Existe_Cidadao_Cnpj(_cpfcnpj);
            }

            if (_codigo > 0) {
                ViewBag.Result = "Já existe um cadastro com este Cpf/Cnpj!";
                return View(model);
            }

            TempData["c"] = model.CpfCnpj;
            return RedirectToAction("Cidadao_add");
        }

        [Route("Cidadao_add")]
        [HttpGet]
        public ActionResult Cidadao_add() {
            if (Session["hashid"] == null)
                return RedirectToAction("Login", "Home");

            CidadaoViewModel model = new CidadaoViewModel();
            Cidadao_bll cidadaoRepository = new Cidadao_bll(_connection);
            List<Profissao> Lista = cidadaoRepository.Lista_Profissao();
            ViewBag.Lista_Profissao = new SelectList(Lista, "Codigo", "Nome");

            List<Logradouro> Lista_Logradouro = new List<Logradouro>();
            ViewBag.LogradouroR = new SelectList(Lista_Logradouro, "Codlogradouro", "Endereco");
            ViewBag.LogradouroC = new SelectList(Lista_Logradouro, "Codlogradouro", "Endereco");

            model.EnderecoR = new EnderecoStruct();
            model.EnderecoC = new EnderecoStruct();
            var _cpfcnpj = TempData["c"];
            if(_cpfcnpj==null)
                return RedirectToAction("Cidadao_chk");
            else
                model.CpfCnpj = TempData["c"].ToString();
            return View(model);
        }

        [Route("Cidadao_add")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Cidadao_add(CidadaoViewModel model, string action) {
            if (Session["hashid"] == null)
                return RedirectToAction("Login", "Home");
            int _cep;
            

            Cidadao_bll cidadaoRepository = new Cidadao_bll(_connection);
            List<Profissao> Lista = cidadaoRepository.Lista_Profissao();
            ViewBag.Lista_Profissao = new SelectList(Lista, "Codigo", "Nome");
            List<Logradouro> Lista_LogradouroR = new List<Logradouro>();
            List<Logradouro> Lista_LogradouroC = new List<Logradouro>();
            Endereco_bll enderecoRepository = new Endereco_bll(_connection);

            if (action == "btnCepR") {
                 _cep = Convert.ToInt32(Functions.RetornaNumero(model.EnderecoR.Cep));
                 var cepObj = GTI_Mvc.Classes.Cep.Busca_CepDB(_cep);
                if (cepObj.CEP != null) {
                    string rua = cepObj.Endereco;
                    if (rua.IndexOf('-') > 0) {
                        rua = rua.Substring(0, rua.IndexOf('-'));
                    }
                    
                    List<string> Lista_Tmp = enderecoRepository.Retorna_CepDB_Logradouro(_cep);
                    int s = 1;
                    foreach (string item in Lista_Tmp) {
                        Lista_LogradouroR.Add(new Logradouro() { Codlogradouro = s, Endereco = item.ToUpper() });
                        s++;
                    }
                    ViewBag.LogradouroR = new SelectList(Lista_LogradouroR, "Codlogradouro", "Endereco");

                    Bairro bairro = enderecoRepository.Retorna_CepDB_Bairro(_cep);
                    if (bairro != null) {
                        model.EnderecoR.CodigoBairro = bairro.Codbairro;
                        model.EnderecoR.NomeBairro = bairro.Descbairro;
                    }
                    Cidade cidade = enderecoRepository.Retorna_CepDB_Cidade(_cep);
                    if (cidade != null) {
                        model.EnderecoR.CodigoCidade = cidade.Codcidade;
                        model.EnderecoR.NomeCidade = cidade.Desccidade;
                    }
                    model.EnderecoR.UF = cepObj.Estado;

                } else {
                    model.EnderecoR.CodLogradouro = 0;
                    model.EnderecoR.Endereco = "";
                    model.EnderecoR.CodigoBairro = 0;
                    model.EnderecoR.NomeBairro = "";
                    model.EnderecoR.CodigoCidade = 0;
                    model.EnderecoR.NomeCidade = "";
                    model.EnderecoR.Numero = 0;
                    model.EnderecoR.Complemento = "";
                    model.EnderecoR.UF = "";

                    ViewBag.Error = "* Cep do endereço residencial não localizado.";
                    return View(model);
                }
            } else {
                if (action == "btnCepC") {
                    _cep = Convert.ToInt32(Functions.RetornaNumero(model.EnderecoC.Cep));
                    var cepObjC = GTI_Mvc.Classes.Cep.Busca_CepDB(_cep);
                    if (cepObjC.CEP != null) {
                        string rua = cepObjC.Endereco;
                        if (rua.IndexOf('-') > 0) {
                            rua = rua.Substring(0, rua.IndexOf('-'));
                        }

                        Endereco_bll EnderecoCepository = new Endereco_bll(_connection);
                        List<string> Lista_Tmp = EnderecoCepository.Retorna_CepDB_Logradouro(_cep);
                        int s = 1;
                        foreach (string item in Lista_Tmp) {
                            Lista_LogradouroC.Add(new Logradouro() { Codlogradouro = s, Endereco = item.ToUpper() });
                            s++;
                        }
                        ViewBag.LogradouroC = new SelectList(Lista_LogradouroC, "Codlogradouro", "Endereco");


                        Bairro bairro = EnderecoCepository.Retorna_CepDB_Bairro(_cep);
                        if (bairro != null) {
                            model.EnderecoC.CodigoBairro = bairro.Codbairro;
                            model.EnderecoC.NomeBairro = bairro.Descbairro;
                        }
                        Cidade cidade = EnderecoCepository.Retorna_CepDB_Cidade(_cep);
                        if (cidade != null) {
                            model.EnderecoC.CodigoCidade = cidade.Codcidade;
                            model.EnderecoC.NomeCidade = cidade.Desccidade;
                        }
                        model.EnderecoC.UF = cepObjC.Estado;

                    } else {
                        model.EnderecoC.CodLogradouro = 0;
                        model.EnderecoC.Endereco = "";
                        model.EnderecoC.CodigoBairro = 0;
                        model.EnderecoC.NomeBairro = "";
                        model.EnderecoC.CodigoCidade = 0;
                        model.EnderecoC.NomeCidade = "";
                        model.EnderecoC.Numero = 0;
                        model.EnderecoC.Complemento = "";
                        model.EnderecoC.UF = "";

                        ViewBag.Error = "* Cep do endereço comercial não localizado.";
                        return View(model);
                    }
                } else {
                    if (action == "btnCancel") {
                        return RedirectToAction("Cidadao_menu");
                    } else {
                        if (action == "btnValida" || action=="Cidadao_add") {
                            int _cod=Grava_Cidadao(model,true);
                            TempData["cod"] = _cod;
                            return RedirectToAction("Cidadao_vw");
                        }
                    }
                }
            }

            if (ViewBag.LogradouroR==null && !string.IsNullOrEmpty(model.EnderecoR.Cep)){
                _cep = Convert.ToInt32(Functions.RetornaNumero(model.EnderecoR.Cep));
                List<string> Lista_Tmp = enderecoRepository.Retorna_CepDB_Logradouro(_cep);
                int s = 1;
                foreach (string item in Lista_Tmp) {
                    Lista_LogradouroR.Add(new Logradouro() { Codlogradouro = s, Endereco = item.ToUpper() });
                    s++;
                }
                ViewBag.LogradouroR = new SelectList(Lista_LogradouroR, "Codlogradouro", "Endereco");
            } else {
                ViewBag.LogradouroR = new SelectList(Lista_LogradouroR, "Codlogradouro", "Endereco");
            }
            if (ViewBag.LogradouroC==null && !string.IsNullOrEmpty(model.EnderecoC.Cep)) {
                _cep = Convert.ToInt32(Functions.RetornaNumero( model.EnderecoC.Cep));
                List<string> Lista_Tmp = enderecoRepository.Retorna_CepDB_Logradouro(_cep);
                int s = 1;
                foreach (string item in Lista_Tmp) {
                    Lista_LogradouroC.Add(new Logradouro() { Codlogradouro = s, Endereco = item.ToUpper() });
                    s++;
                }

GTI_MVC/Views/Cidadao/Cidadao_chk.cshtml
@model GTI_Mvc.ViewModels.CidadaoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Cadastrar novo cidadão";
}

<style>
    .center {
        margin: auto;
    }

    .actionlink:hover {
        color: darkgreen;
    }

    .actionlink {
        color: darkslateblue;
    }

    .card-header {
        background-color: mistyrose;
        color: brown;
        font-size: 14px
    }

    .card {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    .card-footer {
        background-color: whitesmoke;
        font-size: 14px
    }

    .btn-primary {
        background-color: steelblue;
    }

    .btn {
        font-size: 14px;
        border-radius: 4px;
    }

    .ui-dialog-titlebar-close {
        visibility: hidden;
    }

    .uppercase {
        text-transform: uppercase
    }


    .btEdit {
        background: none !important;
        border: none;
        padding: 0 !important;
        font-family: arial, sans-serif;
        color: darkslateblue;
        text-decoration: underline;
        cursor: pointer;
        
    }
        .btEdit:hover {
            color: darkgreen;
        }
</style>

@{var res = @ViewBag.Result;}
<div class="center" style="width:700px">

    @using (Html.BeginForm("Cidadao_chk", "Cidadao", FormMethod.Post, new { @id = "MainForm" })) {
        @Html.AntiForgeryToken()
        <div class="container" style="width:550px">
            <div class="card">
                <div class="card-header">Cadastrar novo cidadão</div>
                <div class="card-body">

                    <div>
                        <table style="font-size:13px;width:500px">
                            <tr style="height:25px">
                                <td style="width:80px">
                                    <span style="font-weight:normal">Cpf/Cnpj:</span>
                                </td>
                                <td>
                                    @Html.TextBoxFor(m => m.CpfCnpj, new { @id = "cpfcnpj", @style = "Width:160px" })
                                </td>
                            </tr>
                        </table>
                    </div>


                    <br />
                    <div >
                        <button type="submit" id="btnOk" class="btn btn-primary" name="action" value="btnValida"> Continuar</button>&nbsp;&nbsp;

                    </div>


                </div>
                <div class="card-footer">
                    @Html.ActionLink("Retornar ao menu de opções", "Cidadao_menu", "Cidadao", null, new { @class = "actionlink" })<br />
                    @Html.ActionLink("Retornar ao menu principal", "Login_gti", "Home", null, new { @class = "actionlink" })
                </div>
            </div>

        
        </div>
    }
</div>
<div id="msgBox1" title="Atenção" style='display: none;'>
    <br />
    <label id="lblMsg"></label>
</div>

<div id="msgBoxBag" title="Atenção" style='display: none;'>
    <br />
    <p>@ViewBag.Result</p>
</div>

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            
            $("#btnOk").click(function () {
                return ValidateForm();
            });

            $("input[id*='cpfcnpj']").inputmask({
                mask: ['999.999.999-99', '99.999.999/9999-99'],
                keepStatic: true
            });
            $('#msgBox1').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });


            $('#msgBoxBag').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $(".foo .ui-dialog-title").css("font-size", "13px");
            $(".foo .ui-widget-content").css("font-size", "13px");

            var _res = '@res';
            if (_res != "") {
                $('#msgBoxBag').dialog('open');
                return false;
            } else {
                return true;
            }
        });

        function ValidateForm() {
            var _cpf = document.getElementById('cpfcnpj').value;

            //*** Valida CpfCnpj ***
            if (_cpf.length == 14) {
                if (!valida_Cpf(_cpf)) {
                    document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                    $('#msgBox1').dialog('open');
                    return false;
                }
            } else {
                if (_cpf.length == 18) {
                    if (!valida_Cnpj(_cpf)) {
                        document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                        $('#msgBox1').dialog('open');
                        return false;
                    }
                } else {
                    document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                    $('#msgBox1').dialog('open');
                    return false;
                }
            }
        }

    </script>
}

GTI_MVC/Views/Cidadao/Cidadao_chkedt.cshtml
@model GTI_Mvc.ViewModels.CidadaoViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Consulta ao cadastro cidadão";
}

<style>
    .center {
        margin: auto;
    }

    .actionlink:hover {
        color: darkgreen;
    }

    .actionlink {
        color: darkslateblue;
    }

    .card-header {
        background-color: mistyrose;
        color: brown;
        font-size: 14px
    }

    .card {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    .card-footer {
        background-color: whitesmoke;
        font-size: 14px
    }

    .btn-primary {
        background-color: steelblue;
    }

    .btn {
        font-size: 14px;
        border-radius: 4px;
    }

    .ui-dialog-titlebar-close {
        visibility: hidden;
    }

    .uppercase {
        text-transform: uppercase
    }


    .btEdit {
        background: none !important;
        border: none;
        padding: 0 !important;
        font-family: arial, sans-serif;
        color: darkslateblue;
        text-decoration: underline;
        cursor: pointer;
        
    }
        .btEdit:hover {
            color: darkgreen;
        }
</style>

@{var res = @ViewBag.Result;}
<div class="center" style="width:700px">

    @using (Html.BeginForm("Cidadao_chkedt", "Cidadao", FormMethod.Post, new { @id = "MainForm" })) {
        @Html.AntiForgeryToken()<div class="container" style="width:550px">
            <div class="card">
                <div class="card-header">Consulta ao cadastro cidadão</div>
                <div class="card-body">

                    <div>
                        <table style="font-size:13px;width:500px">
                            <tr style="height:25px">
                                <td style="width:80px">
                                    <span style="font-weight:normal">Código:</span>
                                </td>
                                <td>
                                    @if (Model.Codigo > 0) {
                                        @Html.TextBoxFor(m => m.Codigo, new { @id = "codigo", @style = "Width:90px" })
                                    } else {
                                        @Html.TextBoxFor(m => m.Codigo, new { @id = "codigo", @style = "Width:90px",@Value="" })
                                    }
                                                            </td>
                            </tr>
                            <tr style="height:25px">
                                <td style="width:80px">
                                    <span style="font-weight:normal">Cpf/Cnpj:</span>
                                </td>
                                <td>
                                    @Html.TextBoxFor(m => m.CpfCnpj, new { @id = "cpfcnpj", @style = "Width:160px" })
                                </td>
                            </tr>
                        </table>
                    </div>


                    <br />
                    <div >
                        <button type="submit" id="btnOk" class="btn btn-primary" name="action" value="btnValida"> Continuar</button>&nbsp;&nbsp;

                    </div>


                </div>
                <div class="card-footer">
                    @Html.ActionLink("Retornar ao menu de opções", "Cidadao_menu", "Cidadao", null, new { @class = "actionlink" })<br />
                    @Html.ActionLink("Retornar ao menu principal", "Login_gti", "Home", null, new { @class = "actionlink" })
                </div>
            </div>

        
        </div>
    }
</div>
<div id="msgBox1" title="Atenção" style='display: none;'>
    <br />
    <label id="lblMsg"></label>
</div>

<div id="msgBoxBag" title="Atenção" style='display: none;'>
    <br />
    <p>@ViewBag.Result</p>
</div>

@section scripts{

    <script type="text/javascript">
        $(document).ready(function () {
            
            $("#btnOk").click(function () {
                return ValidateForm();
            });

            $("input[id*='cpfcnpj']").inputmask({
                mask: ['999.999.999-99', '99.999.999/9999-99'],
                keepStatic: true
            });
            $("input[id*='codigo']").inputmask({
                mask: ['999999'],
                keepStatic: true
            });

            $('#msgBox1').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });


            $('#msgBoxBag').dialog({
                autoOpen: false,
                resizable: false,
                draggable: false,
                position: { my: 'top', at: 'top+300' },
                height: "auto",
                width: 340,
                modal: true,
                dialogClass: "foo",
                buttons: {
                    "OK": function () {
                        $(this).dialog("close");
                    }
                }
            });

            $(".foo .ui-dialog-title").css("font-size", "13px");
            $(".foo .ui-widget-content").css("font-size", "13px");

            var _res = '@res';
            if (_res != "") {
                $('#msgBoxBag').dialog('open');
                return false;
            } else {
                return true;
            }
        });

        function ValidateForm() {
            var _cpf = document.getElementById('cpfcnpj').value;
            var _codigo = document.getElementById('codigo').value;

            if ((_codigo == "" || parseInt(_codigo) == 0) && _cpf.length==0 ) {
                document.getElementById('lblMsg').innerHTML = "Digite o código cidadão ou informe o Cpf/Cnpj!";
                $('#msgBox1').dialog('open');
                return false;
            }

            if (( parseInt(_codigo) > 0) && _cpf.length > 0) {
                document.getElementById('lblMsg').innerHTML = "Digite o código cidadão ou informe o Cpf/Cnpj!";
                $('#msgBox1').dialog('open');
                return false;
            }


            if (_cpf.length > 0) {
                //*** Valida CpfCnpj ***
                if (_cpf.length == 14) {
                    if (!valida_Cpf(_cpf)) {
                        document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                        $('#msgBox1').dialog('open');
                        return false;
                    }
                } else {
                    if (_cpf.length == 18) {
                        if (!valida_Cnpj(_cpf)) {
                            document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                            $('#msgBox1').dialog('open');
                            return false;
                        }
                    } else {
                        document.getElementById('lblMsg').innerHTML = "Nº de Cpf/Cnpj inválido!";
                        $('#msgBox1').dialog('open');
                        return false;
                    }
                }
            }

        }

    </script>
}

GTI_MVC/Views/Cidadao/Cidadao_menu.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Menu de Opções";
}
<link href="~/css/gti.css" rel="stylesheet" />
<style>
    .center {
        margin: auto;
    }

    .actionlink:hover {
        color: darkgreen;
    }

    .actionlink {
        color: darkslateblue;
        font-size:14px;
    }
    .card-header {
        background-color: mistyrose;
        color: brown;
        font-size: 14px
    }

    .card {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 14px;
    }

    .card-footer {
        background-color: whitesmoke;
        font-size: 14px
    }

    .btn-primary {
        background-color: steelblue;
    }

    .btn {
        font-size: 14px;
        border-radius: 4px;
    }

    .errorlabel {
        font-weight: normal;
        color: red;
        padding-left: 13px;
        font-size: 13px;
        font-family: Arial, Helvetica, sans-serif;
    }
</style>
<br />

<div class="center">
    <div class="container" style="width:350px">
        <div class="card">
            <div class="card-header">Cadastro Cidadão </div>
            <div class="card-body">
                @Html.ActionLink("Cadastrar um novo cidadão", "Cidadao_chk", "Cidadao", null, new { @class = "actionlink" })<br />
                @Html.ActionLink("Consultar cidadão cadastrado", "Cidadao_chkedt", "Cidadao", null, new { @class = "actionlink" })<br />
            </div>
            <div class="card-footer">
                @Html.ActionLink("Retornar ao menu de opções", "sysMenu", "Home", null, new { @class = "actionlink" })<br />
                @Html.ActionLink("Retornar ao menu principal", "Login_gti", "Home", null, new { @class = "actionlink" })
            </div>
        </div>
 
    
    </div>
</div>